// packages/gateway/src/ui/pages/run-detail.tsx
import type { RunDetail } from '../../types';
import { StatusBadge } from '../components/status-badge';

type RunDetailPageProps = {
  events: Array<{ event: string; detail: unknown; timestamp: number; sequence?: number }>;
  run: RunDetail;
  streamingAssistantContent: string;
  toolActivity: string[];
};

function formatDetail(detail: unknown): string {
  if (detail === undefined) {
    return '—';
  }

  if (typeof detail === 'string') {
    return detail;
  }

  if (typeof detail === 'number' || typeof detail === 'boolean' || typeof detail === 'bigint') {
    return String(detail);
  }

  if (detail instanceof Error) {
    return detail.message;
  }

  if (typeof detail === 'symbol') {
    return detail.description ? `Symbol(${detail.description})` : 'Symbol()';
  }

  try {
    return JSON.stringify(detail, null, 2);
  } catch {
    return Object.prototype.toString.call(detail);
  }
}

export function RunDetailPage({
  run,
  events,
  streamingAssistantContent,
  toolActivity,
}: RunDetailPageProps) {
  return (
    <main className="page-run-detail">
      <h1>
        Run {run.id} <StatusBadge status={run.status} />
      </h1>
      <section>
        <h2>Summary</h2>
        <dl>
          <dt>Session</dt>
          <dd>{run.sessionId || '—'}</dd>
          <dt>Steps</dt>
          <dd>{run.steps}</dd>
          <dt>Usage</dt>
          <dd>
            prompt: {run.usage.prompt}, completion: {run.usage.completion}, total: {run.usage.total}
          </dd>
          <dt>Finish Reason</dt>
          <dd>{run.finishReason ?? '—'}</dd>
          {run.error ? (
            <>
              <dt>Error</dt>
              <dd className="error">{run.error}</dd>
            </>
          ) : null}
        </dl>
      </section>

      {streamingAssistantContent ? (
        <section>
          <h2>Streaming Output</h2>
          <pre>{streamingAssistantContent}</pre>
        </section>
      ) : null}

      {toolActivity.length > 0 ? (
        <section>
          <h2>Tool Activity</h2>
          <ul>
            {toolActivity.map((entry, index) => (
              <li key={`${entry}-${index}`}>{entry}</li>
            ))}
          </ul>
        </section>
      ) : null}

      <section>
        <h2>Steps</h2>
        {run.stepDetails.length === 0 ? (
          <p>No completed steps yet.</p>
        ) : (
          <ol className="run-step-list">
            {run.stepDetails.map((step) => (
              <li key={`step-${step.step}`}>
                <h3>Step {step.step + 1}</h3>
                <p>{step.content || '—'}</p>
                <p>Final: {step.final ? 'yes' : 'no'}</p>
                {step.toolCalls.length > 0 ? (
                  <>
                    <h4>Tool Calls</h4>
                    <pre>{formatDetail(step.toolCalls)}</pre>
                  </>
                ) : null}
                {step.results.length > 0 ? (
                  <>
                    <h4>Results</h4>
                    <pre>{formatDetail(step.results)}</pre>
                  </>
                ) : null}
              </li>
            ))}
          </ol>
        )}
      </section>

      <section>
        <h2>Latest Snapshot</h2>
        <pre>{formatDetail(run.latestSnapshot)}</pre>
      </section>

      <section>
        <h2>Timeline</h2>
        {events.length === 0 ? (
          <p>No events yet.</p>
        ) : (
          <ol className="run-event-list">
            {events.map((event, index) => (
              <li key={`${event.event}-${event.timestamp}-${event.sequence ?? index}`}>
                <strong>{event.event}</strong>
                <div>{new Date(event.timestamp).toLocaleTimeString()}</div>
                <pre>{formatDetail(event.detail)}</pre>
              </li>
            ))}
          </ol>
        )}
      </section>
    </main>
  );
}

// packages/gateway/src/ui/pages/run-detail.svelte
<script lang="ts">
  import { Card } from '@lostgradient/cinder/card';
  import { CodeBlock } from '@lostgradient/cinder/code-block';
  import { DescriptionList } from '@lostgradient/cinder/description-list';
  import { EmptyState } from '@lostgradient/cinder/empty-state';
  import { JsonViewer } from '@lostgradient/cinder/json-viewer';
  import { SectionHeading } from '@lostgradient/cinder/section-heading';
  import { Stat } from '@lostgradient/cinder/stat';
  import { StatGroup } from '@lostgradient/cinder/stat-group';
  import { Timeline } from '@lostgradient/cinder/timeline';
  import type { TimelineEntry, TimelineTone } from '@lostgradient/cinder/timeline';

  import type { RunDetail } from '../../types';
  import StatusBadge from '../components/status-badge.svelte';

  type TimelineEvent = {
    event: string;
    detail: unknown;
    timestamp: number;
    sequence?: number;
  };

  /**
   * Run detail page. Renders the rich view of a single run: summary, usage
   * stats, streaming output, tool activity, per-step cards, the latest
   * conversation snapshot, and an event timeline.
   *
   * All reactive inputs (`run`, `events`, `streamingAssistantContent`,
   * `toolActivity`) are owned by the run-detail store (use-run-detail.svelte.ts)
   * and passed in by {@link app.svelte}. This page is presentational and holds
   * no state or effects of its own.
   */
  let {
    run,
    events,
    streamingAssistantContent,
    toolActivity,
  }: {
    run: RunDetail;
    events: TimelineEvent[];
    streamingAssistantContent: string;
    toolActivity: string[];
  } = $props();

  /** Maps an event name onto a Timeline marker tone. */
  function eventTone(event: string): TimelineTone {
    if (event.endsWith('.completed')) return 'success';
    if (event.endsWith('.error') || event === 'stream:error') return 'error';
    if (event.endsWith('.aborted')) return 'warning';
    return 'info';
  }

  /** Stable, unique key for a timeline event. Mirrors the React row key. */
  function eventKey(event: TimelineEvent, index: number): string {
    return `${event.event}-${event.timestamp}-${event.sequence ?? index}`;
  }

  let summaryItems = $derived([
    { term: 'Session', definition: run.sessionId || '—' },
    { term: 'Steps', definition: String(run.steps) },
    { term: 'Finish Reason', definition: run.finishReason ?? '—' },
    ...(run.error ? [{ term: 'Error', definition: run.error }] : []),
  ]);

  // Timeline's per-entry snippet only receives a `TimelineEntry`, which carries
  // no `detail`. Build the entries plus a parallel id -> detail map so the
  // children snippet can look the raw value back up and hand it to JsonViewer.
  //
  // The displayed time is the UTC clock portion of the ISO string rather than
  // `toLocaleTimeString()`, which is locale- and timezone-dependent: the server
  // and the browser can format the same instant differently, which would cause
  // a hydration mismatch. A fixed UTC HH:MM:SS renders identically on both.
  let timelineEntries = $derived<TimelineEntry[]>(
    events.map((event, index) => {
      const datetime = new Date(event.timestamp).toISOString();
      return {
        id: eventKey(event, index),
        datetime,
        timestamp: `${datetime.slice(11, 19)} UTC`,
        title: event.event,
        tone: eventTone(event.event),
      };
    }),
  );

  let detailById = $derived.by(() => {
    const map = new Map<string, unknown>();
    for (const [index, event] of events.entries()) {
      map.set(eventKey(event, index), event.detail);
    }
    return map;
  });
</script>

<main class="page-run-detail">
  <div class="run-detail-heading">
    <SectionHeading level={2} title={`Run ${run.id}`} />
    <StatusBadge status={run.status} />
  </div>

  <section>
    <SectionHeading level={3} title="Summary" />
    <DescriptionList items={summaryItems} variant="two-column" />
    <StatGroup columns={3} variant="cards" label="Token usage">
      <Stat label="Prompt" value={run.usage.prompt} />
      <Stat label="Completion" value={run.usage.completion} />
      <Stat label="Total" value={run.usage.total} />
    </StatGroup>
  </section>

  {#if streamingAssistantContent}
    <section>
      <SectionHeading level={3} title="Streaming Output" />
      <CodeBlock code={streamingAssistantContent} highlight={false} />
    </section>
  {/if}

  {#if toolActivity.length > 0}
    <section>
      <SectionHeading level={3} title="Tool Activity" />
      <ul class="run-tool-activity">
        {#each toolActivity as entry, index (`${entry}-${index}`)}
          <li>{entry}</li>
        {/each}
      </ul>
    </section>
  {/if}

  <section>
    <SectionHeading level={3} title="Steps" />
    {#if run.stepDetails.length === 0}
      <EmptyState title="No completed steps yet." />
    {:else}
      <div class="run-step-list">
        {#each run.stepDetails as step (step.step)}
          <Card title={`Step ${step.step + 1}`}>
            <p>{step.content || '—'}</p>
            <p>Final: {step.final ? 'yes' : 'no'}</p>
            {#if step.toolCalls.length > 0}
              <SectionHeading level={4} title="Tool Calls" />
              <JsonViewer value={step.toolCalls} />
            {/if}
            {#if step.results.length > 0}
              <SectionHeading level={4} title="Results" />
              <JsonViewer value={step.results} />
            {/if}
          </Card>
        {/each}
      </div>
    {/if}
  </section>

  <section>
    <SectionHeading level={3} title="Latest Snapshot" />
    {#if run.latestSnapshot === undefined}
      <EmptyState title="No snapshot yet." />
    {:else}
      <JsonViewer value={run.latestSnapshot} />
    {/if}
  </section>

  <section>
    <SectionHeading level={3} title="Timeline" />
    {#if timelineEntries.length === 0}
      <EmptyState title="No events yet." />
    {:else}
      <Timeline entries={timelineEntries} label="Run event timeline">
        {#snippet children(entry: TimelineEntry)}
          {@const detail = detailById.get(entry.id)}
          {#if detail !== undefined}
            <JsonViewer value={detail} />
          {/if}
        {/snippet}
      </Timeline>
    {/if}
  </section>
</main>
