// packages/gateway/src/ui/app.svelte
<script lang="ts">
  import { untrack } from 'svelte';

  import type { ConfigurationResponse, RunDetail, RunSummary } from '../types';
  import { createChatStore } from './hooks/use-chat.svelte';
  import { createRunDetailStore } from './hooks/use-run-detail.svelte';
  import { createRunsStore } from './hooks/use-runs.svelte';
  import { createWebSocket } from './hooks/use-websocket.svelte';
  import Layout from './layout.svelte';
  import ChatPage from './pages/chat.svelte';
  import ConfigurationPage from './pages/configuration.svelte';
  import DashboardPage from './pages/dashboard.svelte';
  import RunDetailPage from './pages/run-detail.svelte';
  import { matchRoute } from './router';

  type InitialData = {
    runs?: RunSummary[];
    run?: RunDetail;
    config?: ConfigurationResponse;
  };

  /**
   * Root application component. Single source of truth for the gateway UI:
   * the same component tree renders on the server (svelte/server `render`) and
   * on the client (`hydrate`), so SSR markup and the hydrated app agree for any
   * given `initialData`.
   *
   * It owns the four reactive stores, fans every incoming websocket/SSE frame
   * out to their handlers, drives route-scoped subscriptions, and routes
   * between the four pages inside the shared {@link Layout}.
   */
  let { initialData, pathname }: { initialData: InitialData; pathname: string } = $props();

  const EMPTY_RUN_DETAIL: RunDetail = {
    id: '',
    sessionId: '',
    status: 'running',
    steps: 0,
    usage: { prompt: 0, completion: 0, total: 0 },
    finishReason: undefined,
    error: undefined,
    actionCount: 0,
    events: [],
    stepDetails: [],
    latestSnapshot: undefined,
  };

  const EMPTY_CONFIGURATION: ConfigurationResponse = {
    provider: undefined,
    providers: [],
    maximumSteps: 10,
    systemPrompt: undefined,
    tools: [],
  };

  let route = $derived(matchRoute(pathname));

  // Stores are constructed in dependency order: runs and run-detail first, then
  // chat (which upserts created runs into the runs list), then the websocket
  // whose onMessage fans frames out to all three. The fan-out closure only runs
  // once frames arrive (post-mount), so the earlier stores are already in scope.
  // `initialData` is one-time hydration seed: the root is hydrated once with
  // fixed props, and each store owns its own reactive state thereafter (fed by
  // live frames). `untrack` expresses that deliberate one-time read so it isn't
  // mistaken for a reactive dependency. It is isomorphic, so the SSR and client
  // seeds stay identical.
  const runsStore = createRunsStore(untrack(() => initialData.runs ?? []));
  const runDetailStore = createRunDetailStore(untrack(() => initialData.run ?? EMPTY_RUN_DETAIL));

  const websocketProtocol =
    typeof window !== 'undefined' && window.location.protocol === 'https:' ? 'wss:' : 'ws:';
  const websocketHost = typeof window !== 'undefined' ? window.location.host : '';
  const websocketUrl = `${websocketProtocol}//${websocketHost}/ws`;

  const chatStore = createChatStore({
    subscribe: (runId: string) => websocket.subscribe(runId),
    unsubscribe: (runId: string) => websocket.unsubscribe(runId),
    onRunCreated: (run: RunSummary) => runsStore.upsertRun(run),
  });

  const websocket = createWebSocket({
    url: websocketUrl,
    eventStreamUrl: '/api/v1/events',
    onMessage(frame) {
      runsStore.handleMessage(frame);
      runDetailStore.handleMessage(frame);
      chatStore.handleMessage(frame);
    },
  });

  let isDashboardRoute = $derived(route?.name === 'dashboard');
  let detailRunId = $derived(route?.name === 'run-detail' ? route.params['id'] : undefined);

  // The live transport exposes start()/stop() rather than self-connecting, so
  // the root component owns its lifecycle. This effect runs only on the client
  // (effects never run during SSR), opening the transport on mount and tearing
  // it down on unmount.
  $effect(() => {
    websocket.start();
    return () => websocket.stop();
  });

  // Route-scoped subscriptions: a genuine side effect with cleanup keyed to a
  // reactive route, mirroring the two React useEffects exactly.
  $effect(() => {
    if (!isDashboardRoute) return;
    websocket.subscribe('*');
    return () => websocket.unsubscribe('*');
  });

  $effect(() => {
    const id = detailRunId;
    if (!id) return;
    websocket.subscribe(id);
    return () => websocket.unsubscribe(id);
  });
</script>

<Layout connectionStatus={websocket.status} {pathname}>
  {#if route?.name === 'dashboard'}
    <DashboardPage runs={runsStore.runs} />
  {:else if route?.name === 'run-detail'}
    <RunDetailPage
      run={runDetailStore.run}
      events={runDetailStore.events}
      streamingAssistantContent={runDetailStore.streamingAssistantContent}
      toolActivity={runDetailStore.toolActivity}
    />
  {:else if route?.name === 'configuration'}
    <ConfigurationPage config={initialData.config ?? EMPTY_CONFIGURATION} />
  {:else if route?.name === 'chat'}
    <ChatPage chat={chatStore} />
  {:else}
    <p>Page not found.</p>
  {/if}
</Layout>

// packages/gateway/src/ui/app.tsx
import { useEffect, useRef } from 'react';

import type { ConfigurationResponse, RunDetail, RunSummary, ServerFrame } from '../types';
import { useChat } from './hooks/use-chat';
import { useRunDetail } from './hooks/use-run-detail';
import { useRuns } from './hooks/use-runs';
import { useWebSocket } from './hooks/use-websocket';
import { Layout } from './layout';
import { ChatPage } from './pages/chat';
import { ConfigurationPage } from './pages/configuration';
import { DashboardPage } from './pages/dashboard';
import { RunDetailPage } from './pages/run-detail';
import { matchRoute } from './router';

interface InitialData {
  runs?: RunSummary[];
  run?: RunDetail;
  config?: ConfigurationResponse;
}

export function App({ initialData, pathname }: { initialData: InitialData; pathname: string }) {
  const route = matchRoute(pathname);
  const wsProtocol = window.location.protocol === 'https:' ? 'wss:' : 'ws:';
  const wsUrl = `${wsProtocol}//${window.location.host}/ws`;
  const eventStreamUrl = '/api/v1/events';

  const runsHook = useRuns(initialData.runs ?? []);
  const runDetailHook = useRunDetail(
    initialData.run ?? {
      id: '',
      sessionId: '',
      status: 'running',
      steps: 0,
      usage: { prompt: 0, completion: 0, total: 0 },
      finishReason: undefined,
      error: undefined,
      actionCount: 0,
      events: [],
      stepDetails: [],
      latestSnapshot: undefined,
    },
  );

  // Use a ref for the chat message handler so useWebSocket's onMessage can
  // reference it without a circular hook dependency.
  const chatHandleMessageRef = useRef<(frame: ServerFrame) => void>(() => {});

  const {
    status: connectionStatus,
    subscribe,
    unsubscribe,
  } = useWebSocket({
    url: wsUrl,
    eventStreamUrl,
    onMessage(frame) {
      runsHook.handleMessage(frame);
      runDetailHook.handleMessage(frame);
      chatHandleMessageRef.current(frame);
    },
  });

  // useChat now subscribes to the WebSocket synchronously on run creation,
  // eliminating the race where the run completes before the useEffect-based
  // subscription could fire.
  const chat = useChat({ subscribe, unsubscribe, onRunCreated: runsHook.upsertRun });
  chatHandleMessageRef.current = chat.handleMessage;

  const isDashboardRoute = route?.name === 'dashboard';
  const detailRunId = route?.name === 'run-detail' ? route.params?.['id'] : undefined;
  useEffect(() => {
    if (isDashboardRoute) {
      subscribe('*');
      return () => unsubscribe('*');
    }

    return undefined;
  }, [isDashboardRoute, subscribe, unsubscribe]);

  useEffect(() => {
    if (!detailRunId) return;
    subscribe(detailRunId);
    return () => unsubscribe(detailRunId);
  }, [detailRunId, subscribe, unsubscribe]);

  function renderPage() {
    switch (route?.name) {
      case 'dashboard':
        return <DashboardPage runs={runsHook.runs} />;
      case 'run-detail':
        return (
          <RunDetailPage
            run={runDetailHook.run}
            events={runDetailHook.events}
            streamingAssistantContent={runDetailHook.streamingAssistantContent}
            toolActivity={runDetailHook.toolActivity}
          />
        );
      case 'configuration':
        return (
          <ConfigurationPage
            config={
              initialData.config ?? {
                provider: undefined,
                providers: [],
                maximumSteps: 10,
                systemPrompt: undefined,
                tools: [],
              }
            }
          />
        );
      case 'chat':
        return <ChatPage chat={chat} />;
      default:
        return <p>Page not found.</p>;
    }
  }

  return <Layout connectionStatus={connectionStatus}>{renderPage()}</Layout>;
}
